---
title: "Problem Set 3"
output: html_notebook
author: "Halan Badilla"
---

1. A large medical clinic would like to forecast daily patient visits for purposes of staffing.
  (a) If data is available only for the last month, how does this affect the choice of model-based vs. data-driven methods?
  
  <span style="color:blue">In a data-driven method, with a time frame of a month it may struggle to come up with any significant trends as data-driven methods generally require a more robust amount of data to work effectively. On the other hand, Model-Based methods will still do well in that environment as it is working off pre-existing models so time is not really a factor.</span>
  
  (b) The clinic has access to the admissions data of a nearby hospital. Under what conditions will including the hospital information be potentially useful for forecasting the clinic's daily visits?
  
  <span style="color:blue">The clinic having access to the admissions data of the nearby hospital would help forecasting daily visits a the clinic if there is a strong correlation between clinic and hospital visits, if the trends from the hospital visits affect any trends for the clinic visits and finally, though this is assumed to be true as they're nearby, due to location they are really close so generally people that are close can go to either.</span>
  
  (c) Thus far, the clinic administrator takes a heuristic approach, using the visit numbers from the same day of the previous week as a forecast. What is the advantage of this approach? What is the disadvantage?
  
  <span style="color:blue">The advantage of taking the heuristic approach is that you can get some "quick 'n dirty" forecasts and it would be very simple to apply, however, the big disadvantage is the lack of accuracy and it won't be able to adapt to any change in trends for the visitors that occur..</span>
  
  (d) What level of automation appears to be required for this task? Explain.
  
  <span style="color:blue">Moderate to not much at all. If it is a heuristic approach then it is most likely something that is already known and a sort of "short cut" meaning you can skip a lot of the intricate details. This most likely means that it wouldn't be much moderation as all it should require is extracting the data and plugging it into whatever method is going to be used. </span>
  
  (e) Describe two approaches for improving the current heuristic (naive) forecasting approach using ensembles.
  
  <span style="color:blue"></span>
  
2. The ability to scale up renewable energy, and in particular wind power and speed, is dependent on the ability to forecast its short-term availability. Soman et al. (2010) describe different methods for wind power forecasting (the quote is slightly edited for brevity):^4 

   Persistence Method: This method is also known as 'Naive predictor'. It is assumed that the wind speed at time t + δt  will be the same as it was at time t. Unbelievably, it is more accurate than most of the physical and statistical methods for very-short to short term forecasts...
   Physical Approach: Physical systems use parameterizations based on a detailed physical description of the atmosphere...
   Statistical Approach: The statistical approach is based on training with measurement data and uses difference between the predicted and the actual wind speeds in immediate past to tune model parameters. It is easy to model, inexpensive, and provides timely predictions. It is not based on any predefined mathematical model and rather it is based on patterns...
   Hybrid Approach: In general, the combination of different approaches such as mixing physical and statistical approaches or combining short term and medium-term models, etc., is referred to as a hybrid approach.
   
   (a) For each of the four types of methods, describe whether it is model-based, data-driven, or a combination.
   (b) For each of the four types of methods, describe whether it is based on extrapolation, casual modeling, correlation modeling or a combination.
   (c) Describe the advantages and disadvantages of the hybrid approach.
   
```{r}

```

